/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {};

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button'];
    ADescriptions: typeof import('ant-design-vue/es')['Descriptions'];
    ASpace: typeof import('ant-design-vue/es')['Space'];
    ElButton: typeof import('element-plus/es')['ElButton'];
    ElForm: typeof import('element-plus/es')['ElForm'];
    ElFormItem: typeof import('element-plus/es')['ElFormItem'];
    ElInput: typeof import('element-plus/es')['ElInput'];
    ElSpace: typeof import('element-plus/es')['ElSpace'];
    ElTooltip: typeof import('element-plus/es')['ElTooltip'];
    Header: typeof import('./../src/components/Header/index.vue')['default'];
    NAvatar: typeof import('naive-ui')['NAvatar'];
    NButton: typeof import('naive-ui')['NButton'];
    NCol: typeof import('naive-ui')['NCol'];
    NConfigProvider: typeof import('naive-ui')['NConfigProvider'];
    NDivider: typeof import('naive-ui')['NDivider'];
    NDrawer: typeof import('naive-ui')['NDrawer'];
    NDrawerContent: typeof import('naive-ui')['NDrawerContent'];
    NDropdown: typeof import('naive-ui')['NDropdown'];
    NForm: typeof import('naive-ui')['NForm'];
    NFormItem: typeof import('naive-ui')['NFormItem'];
    NImage: typeof import('naive-ui')['NImage'];
    NInput: typeof import('naive-ui')['NInput'];
    NLayout: typeof import('naive-ui')['NLayout'];
    NLayoutHeader: typeof import('naive-ui')['NLayoutHeader'];
    NLayoutSider: typeof import('naive-ui')['NLayoutSider'];
    NMenu: typeof import('naive-ui')['NMenu'];
    NMessageProvider: typeof import('naive-ui')['NMessageProvider'];
    NModal: typeof import('naive-ui')['NModal'];
    NRow: typeof import('naive-ui')['NRow'];
    NSelect: typeof import('naive-ui')['NSelect'];
    NSpace: typeof import('naive-ui')['NSpace'];
    NSwitch: typeof import('naive-ui')['NSwitch'];
    NUpload: typeof import('naive-ui')['NUpload'];
    RouterLink: typeof import('vue-router')['RouterLink'];
    RouterView: typeof import('vue-router')['RouterView'];
    SvgIcon: typeof import('./../src/components/SvgIcon/index.vue')['default'];
    TAside: typeof import('tdesign-vue')['Aside'];
    TButton: typeof import('tdesign-vue-next')['Button'];
    TContent: typeof import('tdesign-vue')['Content'];
    TFooter: typeof import('tdesign-vue')['Footer'];
    THeader: typeof import('tdesign-vue')['Header'];
    THeadMenu: typeof import('tdesign-vue')['HeadMenu'];
    TIcon: typeof import('tdesign-vue-next')['Icon'];
    TLayout: typeof import('tdesign-vue')['Layout'];
    TMenu: typeof import('tdesign-vue')['Menu'];
    TMenuItem: typeof import('tdesign-vue')['MenuItem'];
    TSpace: typeof import('tdesign-vue-next')['Space'];
  }
}
